import type { Metadata, Viewport } from "next";
import "./globals.css";
import { archivo } from "@/fonts/fonts";
import RootMain from "./RootMain";


export const metadata: Metadata = {
  title: "FunRound",
  description: "Generated by create next app",
};

// to avoid zooming in IOS device while entering details in form
export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

// root layout of website
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={archivo.className}>
       <RootMain>
        {children}
        {/* to display modal wth parallel route */}
        {modal}
       </RootMain>
      </body>
    </html>
  );
}
